# Generated by Django 5.2.17 on 2026-10-01 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_initial_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'cuenta', 'verbose_name_plural': 'cuentas'},
        ),
        migrations.AlterModelOptions(
            name='alternate',
            options={'verbose_name': 'alterno', 'verbose_name_plural': 'alternos'},
        ),
        migrations.AlterModelOptions(
            name='inventoryupdate',
            options={'verbose_name': 'actualización de inventario', 'verbose_name_plural': 'actualizaciones de inventario'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'invitación', 'verbose_name_plural': 'invitaciones'},
        ),
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'membresía', 'verbose_name_plural': 'membresías'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'verbose_name': 'repuesto', 'verbose_name_plural': 'repuestos'},
        ),
        migrations.AlterModelOptions(
            name='partcode',
            options={'verbose_name': 'código de repuesto', 'verbose_name_plural': 'códigos de repuestos'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='stockentry',
            options={'verbose_name': 'movimiento de existencias', 'verbose_name_plural': 'movimientos de existencias'},
        ),
        migrations.AlterModelOptions(
            name='supplieritem',
            options={'verbose_name': 'artículo del proveedor', 'verbose_name_plural': 'artículos del proveedor'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, to='mall.role', verbose_name='roles'),
        ),
        migrations.AlterField(
            model_name='alternate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AlterField(
            model_name='alternate',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alternates', to='mall.part', verbose_name='repuesto del catálogo'),
        ),
        migrations.AlterField(
            model_name='alternate',
            name='replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replaces', to='mall.part', verbose_name='repuesto alterno'),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.supplieritem', verbose_name='artículo del proveedor'),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='key',
            field=models.CharField(max_length=120, verbose_name='ID de actualización'),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='payload_hash',
            field=models.CharField(max_length=64, verbose_name='huella de la actualización'),
        ),
        migrations.AlterField(
            model_name='inventoryupdate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.account', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aceptación'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código de invitación'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mall.account', verbose_name='cuenta'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='permission',
            field=models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Administrador'), ('staff', 'Empleado')], default='staff', max_length=20, verbose_name='permiso'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='part',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='part',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='part',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='partcode',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='partcode',
            name='code',
            field=models.CharField(max_length=120, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='partcode',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codes', to='mall.part', verbose_name='repuesto del catálogo'),
        ),
        migrations.AlterField(
            model_name='role',
            name='capability',
            field=models.CharField(choices=[('supplier', 'Proveedor'), ('client', 'Cliente')], max_length=20, verbose_name='tipo de acceso'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.SlugField(unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario responsable'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger', to='mall.supplieritem', verbose_name='artículo del proveedor'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='kind',
            field=models.CharField(choices=[('sync', 'Ajuste de existencias'), ('reserve', 'Reserva'), ('release', 'Liberación de reserva'), ('delivery', 'Entrega')], max_length=20, verbose_name='tipo de movimiento'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='reference',
            field=models.CharField(max_length=120, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='reported_after',
            field=models.PositiveIntegerField(verbose_name='saldo de existencias'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='reserved_after',
            field=models.PositiveIntegerField(verbose_name='saldo de unidades reservadas'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='reserved_delta',
            field=models.IntegerField(default=0, verbose_name='cambio en unidades reservadas'),
        ),
        migrations.AlterField(
            model_name='stockentry',
            name='stock_delta',
            field=models.IntegerField(default=0, verbose_name='cambio en existencias'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='brand',
            field=models.CharField(max_length=120, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='codigo',
            field=models.CharField(max_length=120, verbose_name='código del repuesto'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='description',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='matching_status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('matched', 'Vinculado'), ('review', 'Por revisar')], default='pending', max_length=20, verbose_name='estado de coincidencia'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_items', to='mall.part', verbose_name='repuesto del catálogo'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='reported_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='existencias reportadas'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='unidades reservadas'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='source',
            field=models.CharField(choices=[('upload', 'Carga manual'), ('apiag', 'apiag-cloud')], max_length=20, verbose_name='origen'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.account', verbose_name='proveedor'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='supplier_invent_id',
            field=models.CharField(max_length=120, verbose_name='ID de inventario del proveedor'),
        ),
        migrations.AlterField(
            model_name='supplieritem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='última actualización'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico'),
        ),
    ]
