# Generated by Django 5.2.17 on 2026-10-02 00:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_brand_neutral_skus'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='categoría'),
        ),
        migrations.AddField(
            model_name='part',
            name='subcategory',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='subcategoría'),
        ),
        migrations.CreateModel(
            name='CatalogImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('summary', models.JSONField(default=dict)),
                ('applied_summary', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('completed_batches', models.PositiveIntegerField(default=0)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('total_skus', models.PositiveIntegerField(default=0)),
                ('processed_skus', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('data', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mall.catalogimportjob')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('job', 'index'), name='unique_catalog_import_batch')],
            },
        ),
    ]
