# Generated by Django 5.2.17 on 2026-10-02 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_resumable_catalog_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogClassificationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fingerprint', models.CharField(max_length=64)),
                ('source_skus', models.JSONField(default=list)),
                ('model', models.CharField(max_length=120)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('completed_batches', models.PositiveIntegerField(default=0)),
                ('claim_id', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classification', to='mall.catalogimportjob')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogClassificationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sku', models.CharField(max_length=200)),
                ('source_row', models.PositiveIntegerField()),
                ('target_sku', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('subcategory', models.CharField(blank=True, max_length=120)),
                ('reason', models.TextField()),
                ('confidence', models.FloatField(default=0)),
                ('needs_review', models.BooleanField(default=True)),
                ('evidence', models.JSONField(default=dict)),
                ('candidate_skus', models.JSONField(default=list)),
                ('applied', models.BooleanField(default=False)),
                ('applied_decision', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_suggestions', to='mall.catalogimportjob')),
            ],
            options={
                'ordering': ['source_row', 'source_sku'],
                'constraints': [models.UniqueConstraint(fields=('job', 'source_sku'), name='unique_import_ai_source')],
            },
        ),
    ]
