# Generated by Django 5.2.17 on 2026-10-02 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_supplier_inventory_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRequestSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_submissions', to='mall.account')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=200)),
                ('supplier_name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('reviewed', 'Revisada')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_supplier_requests', to='mall.account')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_supplier_requests', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='mall.clientrequestsubmission')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_supplier_requests', to='mall.account')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRequestLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_invent_id', models.CharField(max_length=120)),
                ('sku', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('codigo', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='mall.part')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mall.supplierrequest')),
                ('supplier_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_lines', to='mall.supplieritem')),
            ],
            options={
                'ordering': ['sku', 'codigo', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientrequestsubmission',
            constraint=models.UniqueConstraint(fields=('client', 'submission_id'), name='unique_client_request_submission'),
        ),
        migrations.AddConstraint(
            model_name='supplierrequest',
            constraint=models.UniqueConstraint(fields=('submission', 'supplier'), name='unique_submission_supplier_request'),
        ),
        migrations.AddConstraint(
            model_name='supplierrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'reviewed'])), name='valid_supplier_request_status'),
        ),
        migrations.AddConstraint(
            model_name='supplierrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'supplier_item'), name='unique_supplier_request_item'),
        ),
        migrations.AddConstraint(
            model_name='supplierrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1), ('quantity__lte', 9999)), name='valid_supplier_request_quantity'),
        ),
    ]
