# Generated by Django 5.2.17 on 2026-10-02 18:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_supplier_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogAssistantJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('unclassified', 'Sin clasificar'), ('all', 'Todo')], max_length=20)),
                ('search', models.CharField(blank=True, max_length=200)),
                ('instructions', models.CharField(blank=True, max_length=2000)),
                ('source_ids', models.JSONField(default=list)),
                ('model', models.CharField(max_length=120)),
                ('completed_batches', models.PositiveIntegerField(default=0)),
                ('claim_id', models.UUIDField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogAssistantSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('proposal', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicado'), ('dismissed', 'Descartado')], default='pending', max_length=10)),
                ('decision', models.JSONField(default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='mall.catalogassistantjob')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.part')),
            ],
            options={
                'ordering': ['position'],
                'constraints': [models.UniqueConstraint(fields=('job', 'source'), name='unique_assistant_source')],
            },
        ),
    ]
