# Generated by Django 5.2.17 on 2026-10-02 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0013_inventory_ai_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_visits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('search', 'Búsqueda'), ('part_view', 'Vista de repuesto'), ('basket_add', 'Agregar a cesta')], max_length=16)),
                ('term', models.CharField(blank=True, max_length=200)),
                ('result_count', models.PositiveIntegerField(null=True)),
                ('sku', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('fingerprint', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.account')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.part')),
                ('supplier_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.supplieritem')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mall.usagevisit')),
            ],
        ),
        migrations.AddIndex(
            model_name='usagevisit',
            index=models.Index(fields=['started_at'], name='usage_visit_started_idx'),
        ),
        migrations.AddConstraint(
            model_name='usagevisit',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='unique_user_usage_visit'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['kind', 'occurred_at'], name='usage_event_kind_date_idx'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['part', 'occurred_at'], name='usage_event_part_date_idx'),
        ),
    ]
