# Generated by Django 5.2.17 on 2026-10-03 01:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0015_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_id', models.UUIDField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DealQuotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('revision', models.PositiveIntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('terms', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('supplier_confirmed_at', models.DateTimeField()),
                ('client_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['revision'],
            },
        ),
        migrations.CreateModel(
            name='DealQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'ordering': ['order_line__sku', 'order_line__codigo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RequestContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lines', models.JSONField(default=list)),
                ('appended', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='supplierrequest',
            name='valid_supplier_request_status',
        ),
        migrations.AddField(
            model_name='clientrequestsubmission',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='handshaked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='supplierrequest',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='supplierrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Enviada · por revisar'), ('reviewed', 'En revisión'), ('quoted', 'Cotizada · por confirmar'), ('adjustment', 'Ajuste solicitado'), ('handshaked', 'Acuerdo confirmado')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='supplierrequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'reviewed', 'quoted', 'adjustment', 'handshaked'])), name='valid_supplier_request_status'),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.account'),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='mall.supplierrequest'),
        ),
        migrations.AddField(
            model_name='dealmessage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.account'),
        ),
        migrations.AddField(
            model_name='dealmessage',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='mall.supplierrequest'),
        ),
        migrations.AddField(
            model_name='dealquotation',
            name='client_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_deal_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealquotation',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='mall.supplierrequest'),
        ),
        migrations.AddField(
            model_name='dealquotation',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='published_deal_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealevent',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mall.dealquotation'),
        ),
        migrations.AddField(
            model_name='dealquotationline',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_lines', to='mall.supplierrequestline'),
        ),
        migrations.AddField(
            model_name='dealquotationline',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='mall.dealquotation'),
        ),
        migrations.AddField(
            model_name='requestcontribution',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='mall.supplierrequest'),
        ),
        migrations.AddField(
            model_name='requestcontribution',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='mall.clientrequestsubmission'),
        ),
        migrations.AddConstraint(
            model_name='dealmessage',
            constraint=models.UniqueConstraint(fields=('order', 'account', 'message_id'), name='unique_deal_message_send'),
        ),
        migrations.AddConstraint(
            model_name='dealquotation',
            constraint=models.UniqueConstraint(fields=('order', 'revision'), name='unique_deal_quote_revision'),
        ),
        migrations.AddConstraint(
            model_name='dealquotation',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='positive_deal_quote_total'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationline',
            constraint=models.UniqueConstraint(fields=('quotation', 'order_line'), name='unique_deal_quote_line'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('quantity__lte', 9999), ('unit_price__gte', 0)), name='valid_deal_quote_line'),
        ),
        migrations.AddConstraint(
            model_name='requestcontribution',
            constraint=models.UniqueConstraint(fields=('submission', 'order'), name='unique_submission_order_contribution'),
        ),
    ]
