# Generated by Django 5.2.17 on 2026-10-03 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0016_deal_workflow'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('result', models.JSONField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.account')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='mall.supplierrequest')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'account', 'operation_id'), name='unique_deal_command')],
            },
        ),
    ]
