# Generated by Django 5.2.17 on 2026-10-05 15:34

import django.db.models.deletion
import mall.media_storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0018_preserve_submission_receipts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=500, storage=mall.media_storage.catalog_storage, upload_to=mall.media_storage.catalog_image_path)),
                ('thumbnail', models.ImageField(max_length=500, storage=mall.media_storage.catalog_storage, upload_to=mall.media_storage.catalog_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('position', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('size_bytes', models.PositiveIntegerField()),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mall.part')),
                ('uploaded_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'imagen del catálogo',
                'verbose_name_plural': 'imágenes del catálogo',
                'ordering': ['position', 'created_at', 'id'],
                'indexes': [models.Index(fields=['part', 'position'], name='part_image_order_idx')],
            },
        ),
    ]
