# Generated by Django 5.2.17 on 2026-10-05 16:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0019_catalog_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingQueue',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('requested', models.PositiveIntegerField(default=0)),
                ('completed', models.PositiveIntegerField(default=0)),
                ('requested_at', models.DateTimeField(auto_now=True)),
                ('lease', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('summary', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=240, unique=True)),
                ('kind', models.CharField(max_length=20)),
                ('fingerprint', models.CharField(max_length=64)),
                ('sources', models.JSONField(default=list)),
                ('candidates', models.JSONField(default=list)),
                ('target_sku', models.CharField(blank=True, max_length=200)),
                ('method', models.CharField(max_length=40)),
                ('reason', models.TextField()),
                ('status', models.CharField(db_index=True, default='review', max_length=20)),
                ('ai', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mall.supplieritem')),
            ],
            options={
                'ordering': ['-updated_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MatchingDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('evidence', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mall.matchingcase')),
            ],
        ),
        migrations.CreateModel(
            name='SupplierCodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mall.part')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('supplier', 'code', 'brand'), name='unique_supplier_code_mapping')],
            },
        ),
    ]
