# Generated by Django 5.2.17 on 2026-10-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0020_smart_supplier_matching'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcode',
            name='kind',
            field=models.CharField(choices=[('alias', 'Equivalencia'), ('oem', 'Referencia OEM'), ('manufacturer', 'Referencia de fabricante')], default='alias', max_length=20),
        ),
        migrations.AddField(
            model_name='partcode',
            name='reference_source',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='fuente de la equivalencia'),
        ),
        migrations.AddField(
            model_name='supplieritem',
            name='references',
            field=models.JSONField(blank=True, default=list, verbose_name='referencias declaradas por el proveedor'),
        ),
    ]
