# Generated by Django 5.2.17 on 2026-10-05 21:22

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0021_partcode_kind_partcode_reference_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=120, verbose_name='grupo')),
                ('name', models.CharField(max_length=120, verbose_name='subgrupo')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('section', models.CharField(default='CARACTERÍSTICAS', max_length=120)),
                ('kind', models.CharField(choices=[('number', 'Medida / decimal'), ('integer', 'Número entero'), ('boolean', 'Sí / No'), ('choice', 'Selección'), ('text', 'Texto')], max_length=12)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('options', models.JSONField(blank=True, default=list)),
                ('required', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='technical_revision',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('generation', models.CharField(blank=True, max_length=120)),
                ('year_from', models.PositiveSmallIntegerField()),
                ('year_to', models.PositiveSmallIntegerField()),
                ('engine', models.CharField(blank=True, max_length=120)),
                ('trim', models.CharField(blank=True, max_length=120)),
                ('transmission', models.CharField(blank=True, max_length=120)),
                ('market', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['make', 'model', 'year_from', 'engine', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('year_to__gte', models.F('year_from'))), name='application_year_order'), models.UniqueConstraint(fields=('make', 'model', 'generation', 'year_from', 'year_to', 'engine', 'trim', 'transmission', 'market'), name='unique_vehicle_application')],
            },
        ),
        migrations.CreateModel(
            name='ItemApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=2000)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('verified', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_applications', to='mall.application')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_applications', to='mall.part')),
            ],
            options={
                'ordering': ['application__make', 'application__model', 'application__year_from', 'id'],
            },
        ),
        migrations.AddField(
            model_name='part',
            name='applications',
            field=models.ManyToManyField(blank=True, related_name='parts', through='mall.ItemApplication', to='mall.application'),
        ),
        migrations.CreateModel(
            name='PartSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_value', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('text_value', models.CharField(blank=True, max_length=2000, null=True)),
                ('source', models.CharField(blank=True, max_length=500)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='mall.part')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalTemplate',
            fields=[
                ('part_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='template', serialize=False, to='mall.parttype')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='parttype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('category'), django.db.models.functions.text.Lower('name'), name='unique_part_type_group_name'),
        ),
        migrations.AddField(
            model_name='part',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='mall.parttype'),
        ),
        migrations.AddField(
            model_name='partspecification',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='mall.technicalfield'),
        ),
        migrations.AddConstraint(
            model_name='itemapplication',
            constraint=models.UniqueConstraint(fields=('part', 'application', 'position'), name='unique_item_application_position'),
        ),
        migrations.AddField(
            model_name='technicalfield',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='mall.technicaltemplate'),
        ),
        migrations.AddIndex(
            model_name='partspecification',
            index=models.Index(fields=['field', 'number_value'], name='spec_numeric_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='partspecification',
            constraint=models.UniqueConstraint(fields=('part', 'field'), name='unique_part_specification'),
        ),
        migrations.AddConstraint(
            model_name='partspecification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boolean_value__isnull', True), ('number_value__isnull', False), ('text_value__isnull', True)), models.Q(('boolean_value__isnull', False), ('number_value__isnull', True), ('text_value__isnull', True)), models.Q(('boolean_value__isnull', True), ('number_value__isnull', True), ('text_value__isnull', False)), _connector='OR'), name='one_specification_value'),
        ),
        migrations.AddConstraint(
            model_name='technicalfield',
            constraint=models.UniqueConstraint(fields=('template', 'key'), name='unique_template_field_key'),
        ),
    ]
