# Generated by Django 5.2.17 on 2026-10-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0023_backfill_part_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorySuggestionCache',
            fields=[
                ('fingerprint', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='catalogassistantjob',
            name='batch_size',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='catalogassistantjob',
            name='metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='catalogassistantjob',
            name='task',
            field=models.CharField(default='grouping', max_length=20),
        ),
    ]
