# Generated by Django 5.2.17 on 2026-10-06 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0026_part_is_oem_matching_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingAuditEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=40)),
                ('object_id', models.CharField(blank=True, default='', max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.account')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_audit_events', to='mall.supplierrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_audit_events', to='mall.account')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['supplier', '-created_at'], name='pricing_audit_supplier_idx')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPricingSettings',
            fields=[
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pricing_settings', serialize=False, to='mall.account')),
                ('default_currency', models.CharField(choices=[('USD', 'USD'), ('PAB', 'PAB')], default='USD', max_length=3)),
                ('usd_pab_parity', models.BooleanField(default=True)),
                ('config_min_permission', models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Administrador'), ('staff', 'Empleado')], default='staff', max_length=10)),
                ('publish_min_permission', models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Administrador'), ('staff', 'Empleado')], default='staff', max_length=10)),
                ('over_request_policy', models.CharField(choices=[('confirm', 'Pedir confirmación'), ('block', 'Bloquear')], default='confirm', max_length=10)),
                ('over_stock_policy', models.CharField(choices=[('confirm', 'Pedir confirmación'), ('block', 'Bloquear')], default='confirm', max_length=10)),
                ('accept_shortfall_policy', models.CharField(choices=[('block', 'Bloquear la confirmación'), ('allow', 'Permitir y avisar al proveedor')], default='block', max_length=10)),
                ('prefill_quantity', models.CharField(choices=[('requested', 'Solicitadas'), ('available', 'Hasta las existencias')], default='requested', max_length=10)),
                ('assistant_enabled', models.BooleanField(default=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('default_currency__in', ['USD', 'PAB'])), name='valid_pricing_default_currency'), models.CheckConstraint(condition=models.Q(('config_min_permission__in', ['owner', 'manager', 'staff'])), name='valid_pricing_config_permission'), models.CheckConstraint(condition=models.Q(('publish_min_permission__in', ['owner', 'manager', 'staff'])), name='valid_pricing_publish_permission'), models.CheckConstraint(condition=models.Q(('over_request_policy__in', ['confirm', 'block'])), name='valid_pricing_over_request_policy'), models.CheckConstraint(condition=models.Q(('over_stock_policy__in', ['confirm', 'block'])), name='valid_pricing_over_stock_policy'), models.CheckConstraint(condition=models.Q(('accept_shortfall_policy__in', ['block', 'allow'])), name='valid_pricing_shortfall_policy'), models.CheckConstraint(condition=models.Q(('prefill_quantity__in', ['requested', 'available'])), name='valid_pricing_prefill_quantity')],
            },
        ),
    ]
