# Generated by Django 5.2.17 on 2026-10-06 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0027_pricing_foundation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealQuotationDraft',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='quote_draft', serialize=False, to='mall.supplierrequest')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PAB', 'PAB')], default='USD', max_length=3)),
                ('terms', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('editing', 'En edición'), ('review_requested', 'Listo para revisión')], default='editing', max_length=20)),
                ('review_requested_at', models.DateTimeField(blank=True, null=True)),
                ('draft_version', models.PositiveIntegerField(default=1)),
                ('last_save_id', models.UUIDField(blank=True, null=True)),
                ('last_save_hash', models.CharField(blank=True, default='', max_length=64)),
                ('order_acknowledgements', models.JSONField(blank=True, default=list)),
                ('pricing_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.dealquotation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('review_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_drafts', to='mall.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealQuotationDraftLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantity_source', models.CharField(choices=[('requested', 'Solicitadas'), ('available', 'Hasta las existencias'), ('previous', 'Versión anterior'), ('manual', 'Manual'), ('assistant', 'Asistente')], default='requested', max_length=10)),
                ('price_source', models.CharField(choices=[('engine', 'Lista o regla'), ('previous', 'Versión anterior'), ('manual', 'Manual'), ('none', 'Sin precio')], default='none', max_length=10)),
                ('engine_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('engine_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('acknowledgements', models.JSONField(blank=True, default=list)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='mall.dealquotationdraft')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.supplierrequestline')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dealquotationdraft',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'PAB'])), name='valid_quote_draft_currency'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationdraft',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['editing', 'review_requested'])), name='valid_quote_draft_status'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationdraftline',
            constraint=models.UniqueConstraint(fields=('draft', 'order_line'), name='unique_quote_draft_line'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationdraftline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('quantity__isnull', True), models.Q(('quantity__gte', 0), ('quantity__lte', 9999)), _connector='OR'), models.Q(('unit_price__isnull', True), ('unit_price__gte', 0), _connector='OR')), name='valid_quote_draft_line'),
        ),
        migrations.AddConstraint(
            model_name='dealquotationdraftline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_source__in', ['requested', 'available', 'previous', 'manual', 'assistant']), ('price_source__in', ['engine', 'previous', 'manual', 'none'])), name='valid_quote_draft_line_sources'),
        ),
    ]
