# Generated by Django 5.2.17 on 2026-10-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0028_quote_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealQuotationLineAudit',
            fields=[
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='audit', serialize=False, to='mall.dealquotationline')),
                ('available_at_quote', models.PositiveIntegerField(blank=True, null=True)),
                ('identity_ok_at_quote', models.BooleanField()),
                ('available_at_accept', models.PositiveIntegerField(blank=True, null=True)),
                ('suggested_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_source', models.CharField(choices=[('engine', 'Lista o regla'), ('previous', 'Versión anterior'), ('manual', 'Manual'), ('none', 'Sin precio'), ('unspecified', 'Sin especificar')], max_length=12)),
                ('quantity_source', models.CharField(choices=[('requested', 'Solicitadas'), ('available', 'Hasta las existencias'), ('previous', 'Versión anterior'), ('manual', 'Manual'), ('assistant', 'Asistente')], max_length=10)),
                ('engine_fingerprint', models.CharField(blank=True, default='', max_length=64)),
                ('explanation', models.JSONField(blank=True, default=dict)),
                ('exceptions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price_source__in', ['engine', 'previous', 'manual', 'none', 'unspecified']), ('quantity_source__in', ['requested', 'available', 'previous', 'manual', 'assistant'])), name='valid_quote_line_audit_sources')],
            },
        ),
        migrations.CreateModel(
            name='DealQuotationAudit',
            fields=[
                ('quotation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='audit', serialize=False, to='mall.dealquotation')),
                ('draft_version', models.PositiveIntegerField(blank=True, help_text='Null when published without a draft (legacy path).', null=True)),
                ('publisher_permission', models.CharField(choices=[('owner', 'Propietario'), ('manager', 'Administrador'), ('staff', 'Empleado')], max_length=10)),
                ('engine_version', models.CharField(blank=True, default='', max_length=20)),
                ('profile_id', models.UUIDField(blank=True, null=True)),
                ('profile_version', models.PositiveIntegerField(blank=True, null=True)),
                ('settings_snapshot', models.JSONField(blank=True, default=dict)),
                ('order_exceptions', models.JSONField(blank=True, default=list)),
                ('accept_check', models.JSONField(blank=True, null=True)),
                ('accept_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('publisher_permission__in', ['owner', 'manager', 'staff'])), name='valid_quote_audit_permission')],
            },
        ),
    ]
