# Generated by Django 5.2.17 on 2026-10-06 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0029_quote_audit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('PAB', 'PAB')], default='USD', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='mall.account')),
            ],
            options={
                'ordering': ['-is_default', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PriceChange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('list_price', 'Precio de lista'), ('floor_price', 'Precio mínimo'), ('discount_group', 'Línea')], max_length=20)),
                ('old_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_text', models.CharField(blank=True, default='', max_length=60)),
                ('new_text', models.CharField(blank=True, default='', max_length=60)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importación'), ('api', 'Integración')], max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='mall.supplieritem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_changes', to='mall.account')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='mall.pricelist')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PriceListEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Importación'), ('api', 'Integración')], default='manual', max_length=10)),
                ('reference', models.CharField(blank=True, default='', max_length=120)),
                ('updated_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_entries', to='mall.supplieritem')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='mall.pricelist')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierItemPricing',
            fields=[
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='pricing', serialize=False, to='mall.supplieritem')),
                ('discount_group', models.CharField(blank=True, default='', help_text='LINEA o familia propia del proveedor.', max_length=60)),
                ('floor_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('supplier', 'code'), name='unique_price_list_code'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('supplier',), name='one_default_price_list'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('active', False), ('is_default', True), _negated=True), name='default_price_list_active'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.CheckConstraint(condition=models.Q(('currency__in', ['USD', 'PAB'])), name='valid_price_list_currency'),
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['supplier', 'item', '-created_at'], name='price_change_item_idx'),
        ),
        migrations.AddIndex(
            model_name='pricechange',
            index=models.Index(fields=['price_list', '-created_at'], name='price_change_list_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricechange',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['list_price', 'floor_price', 'discount_group'])), name='valid_price_change_kind'),
        ),
        migrations.AddIndex(
            model_name='pricelistentry',
            index=models.Index(fields=['item'], name='price_entry_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricelistentry',
            constraint=models.UniqueConstraint(fields=('price_list', 'item'), name='unique_price_list_item'),
        ),
        migrations.AddConstraint(
            model_name='pricelistentry',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gt', 0)), name='positive_list_price'),
        ),
        migrations.AddIndex(
            model_name='supplieritempricing',
            index=models.Index(fields=['supplier', 'discount_group'], name='item_pricing_group_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplieritempricing',
            constraint=models.CheckConstraint(condition=models.Q(('floor_price__isnull', True), ('floor_price__gte', 0), _connector='OR'), name='valid_item_floor_price'),
        ),
    ]
