# Generated by Django 5.2.17 on 2026-10-06 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0030_price_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Lista para aplicar'), ('review', 'Sin cambios aplicables'), ('importing', 'Aplicando'), ('completed', 'Completada')], default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('summary', models.JSONField(default=dict)),
                ('applied_summary', models.JSONField(default=dict)),
                ('preview', models.JSONField(default=dict)),
                ('rejected_rows', models.JSONField(default=list)),
                ('lists_to_create', models.JSONField(default=list)),
                ('big_change_acknowledged', models.BooleanField(default=False)),
                ('completed_batches', models.PositiveIntegerField(default=0)),
                ('total_batches', models.PositiveIntegerField(default=0)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('processed_rows', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_import_jobs', to='mall.account')),
            ],
        ),
        migrations.CreateModel(
            name='PriceImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('data', models.JSONField(default=list)),
                ('fingerprint', models.CharField(max_length=64)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='mall.priceimportjob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='priceimportjob',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['ready', 'review', 'importing', 'completed'])), name='valid_price_import_status'),
        ),
        migrations.AddConstraint(
            model_name='priceimportbatch',
            constraint=models.UniqueConstraint(fields=('job', 'index'), name='unique_price_import_batch'),
        ),
    ]
