# Generated by Django 5.2.17 on 2026-10-06 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0031_price_import'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPricingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fallback_to_default', models.BooleanField(default=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('preferred_currency', models.CharField(blank=True, default='', max_length=3)),
                ('default_terms', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('customer_code', models.CharField(blank=True, default='', max_length=40)),
                ('version', models.PositiveIntegerField(default=1)),
                ('last_operation_id', models.UUIDField(blank=True, null=True)),
                ('last_payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_profiles', to='mall.account')),
                ('price_list', models.ForeignKey(blank=True, help_text='Null: la lista predeterminada del proveedor.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='mall.pricelist')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_profiles', to='mall.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('scope', models.CharField(choices=[('all', 'Todos tus clientes'), ('client', 'Un cliente')], max_length=10)),
                ('target', models.CharField(choices=[('all', 'Todos los artículos'), ('line', 'Línea'), ('brand', 'Marca'), ('item', 'Un artículo')], max_length=10)),
                ('target_value', models.CharField(blank=True, default='', help_text='LINEA o marca, en mayúsculas.', max_length=120)),
                ('kind', models.CharField(choices=[('discount', 'Descuento %'), ('net_price', 'Precio neto')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(blank=True, default='', max_length=3)),
                ('min_quantity', models.PositiveSmallIntegerField(default=1)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('operation_id', models.UUIDField(blank=True, null=True)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='mall.supplieritem')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rules', to='mall.clientpricingprofile')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='mall.account')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-active', 'name', 'created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='clientpricingprofile',
            constraint=models.UniqueConstraint(fields=('supplier', 'client'), name='unique_client_pricing_profile'),
        ),
        migrations.AddConstraint(
            model_name='clientpricingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('supplier', models.F('client')), _negated=True), name='profile_distinct_accounts'),
        ),
        migrations.AddConstraint(
            model_name='clientpricingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lt', 100)), name='valid_profile_discount'),
        ),
        migrations.AddConstraint(
            model_name='clientpricingprofile',
            constraint=models.CheckConstraint(condition=models.Q(('preferred_currency__in', ['', 'USD', 'PAB'])), name='valid_profile_currency'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['supplier', 'active'], name='pricing_rule_supplier_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['profile'], name='pricing_rule_profile_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['item'], name='pricing_rule_item_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('profile__isnull', False), ('scope', 'client')), models.Q(('profile__isnull', True), ('scope', 'all')), _connector='OR'), name='pricing_rule_scope'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('item__isnull', False), ('target', 'item'), ('target_value', '')), models.Q(('item__isnull', True), ('target__in', ['line', 'brand']), models.Q(('target_value', ''), _negated=True)), models.Q(('item__isnull', True), ('target', 'all'), ('target_value', '')), _connector='OR'), name='pricing_rule_target'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', ''), ('kind', 'discount'), ('value__gt', 0), ('value__lt', 100)), models.Q(('currency__in', ['USD', 'PAB']), ('kind', 'net_price'), ('target', 'item'), ('value__gt', 0)), _connector='OR'), name='pricing_rule_value'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 1), ('min_quantity__lte', 9999)), name='pricing_rule_quantity'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='pricing_rule_dates'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_id__isnull', False)), fields=('supplier', 'operation_id'), name='unique_pricing_rule_operation'),
        ),
    ]
