# Generated by Django 5.2.17 on 2026-10-06 13:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0032_client_profiles_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAssistantRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_version', models.PositiveIntegerField(default=0)),
                ('input_fingerprint', models.CharField(max_length=64)),
                ('engine_version', models.CharField(default='quote-assistant-v1', max_length=30)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('claimed', 'En curso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='claimed', max_length=10)),
                ('claim_expires_at', models.DateTimeField(blank=True, null=True)),
                ('cached', models.BooleanField(default=False)),
                ('billable', models.BooleanField(default=False)),
                ('output', models.JSONField(blank=True, default=dict)),
                ('decisions', models.JSONField(blank=True, default=dict)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('estimated_cost_micro_usd', models.BigIntegerField(default=0)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('base_quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.dealquotation')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assistant_runs', to='mall.supplierrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.account')),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='dealquotationlineaudit',
            name='assistant_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.quoteassistantrun'),
        ),
        migrations.CreateModel(
            name='AIUsageRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=40)),
                ('day', models.DateField()),
                ('calls', models.PositiveIntegerField(default=0)),
                ('cached_calls', models.PositiveIntegerField(default=0)),
                ('failed_calls', models.PositiveIntegerField(default=0)),
                ('input_tokens', models.PositiveBigIntegerField(default=0)),
                ('output_tokens', models.PositiveBigIntegerField(default=0)),
                ('thinking_tokens', models.PositiveBigIntegerField(default=0)),
                ('cost_micro_usd', models.PositiveBigIntegerField(default=0)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='mall.account')),
            ],
            options={
                'indexes': [models.Index(fields=['feature', 'day'], name='ai_usage_feature_day_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('account__isnull', False)), fields=('account', 'feature', 'day'), name='unique_ai_usage_account_day'), models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('feature', 'day'), name='unique_ai_usage_platform_day')],
            },
        ),
        migrations.AddIndex(
            model_name='quoteassistantrun',
            index=models.Index(fields=['order', '-created_at'], name='assistant_run_order_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteassistantrun',
            index=models.Index(fields=['input_fingerprint', 'status'], name='assistant_run_cache_idx'),
        ),
        migrations.AddConstraint(
            model_name='quoteassistantrun',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['claimed', 'completed', 'failed'])), name='valid_quote_assistant_run_status'),
        ),
        migrations.AddConstraint(
            model_name='quoteassistantrun',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_cost_micro_usd__gte', 0)), name='valid_quote_assistant_run_cost'),
        ),
    ]
