# Generated by Django 5.2.17 on 2026-10-06 20:59

import json
from pathlib import Path

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone

FIXTURE = Path(__file__).resolve().parent.parent / 'fixtures' / 'catalog_code_suffixes.json'
FIELDS = ('match', 'cls', 'tag_kind', 'variant_kind', 'attribution', 'creates_company_reference', 'scope_overrides', 'confidence',
          'status', 'owner_confirmed', 'proposed_label', 'legacy_company_registry', 'notes', 'stats')


def seed(apps, schema_editor):
    """Idempotent: loads tokens that are missing, never overwrites an edited row. The owner confirmed the 44 seed rows that
    needed confirmation (decision of 2026-10-06); each gets an audit row."""
    Suffix = apps.get_model('mall', 'CatalogCodeSuffix')
    Change = apps.get_model('mall', 'CatalogCodeSuffixChange')
    db = schema_editor.connection.alias
    rows = json.loads(FIXTURE.read_text(encoding='utf-8'))['rows']
    existing = set(Suffix.objects.using(db).values_list('token', flat=True))
    now = timezone.now()
    new = [r for r in rows if r['token'] not in existing]
    Suffix.objects.using(db).bulk_create([Suffix(token=r['token'], version=1, confirmed_at=now if r['owner_confirmed'] else None,
                                                 **{f: r[f] for f in FIELDS}) for r in new], batch_size=200)
    ids = dict(Suffix.objects.using(db).values_list('token', 'pk'))
    for r in new:
        if r['alias_of']:
            Suffix.objects.using(db).filter(pk=ids[r['token']]).update(alias_of_id=ids[r['alias_of']])
    Change.objects.using(db).bulk_create([Change(
        suffix_id=ids[r['token']], token=r['token'], action='seed_confirm', version=1, note='Decisión del propietario del 2026-10-06',
        before={'status': r['seed_status'], 'owner_confirmed': False},
        after={'cls': r['cls'], 'tag_kind': r['tag_kind'], 'variant_kind': r['variant_kind'], 'attribution': r['attribution'],
               'status': r['status'], 'owner_confirmed': True}) for r in new if r.get('seed_status')])


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0033_quote_assistant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCodeSuffix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60, unique=True)),
                ('match', models.CharField(choices=[('exact', 'Exacto'), ('shape', 'Forma')], default='exact', max_length=5)),
                ('cls', models.CharField(choices=[('TAG', 'Etiqueta'), ('VARIANT', 'Variante'), ('UNKNOWN', 'Desconocido')], default='UNKNOWN', max_length=7)),
                ('tag_kind', models.CharField(blank=True, choices=[('company_code', 'Código de empresa'), ('brand', 'Marca'), ('house_brand', 'Marca propia'), ('origin', 'Origen'), ('genuine', 'Genuino'), ('supplier_marker', 'Marcador de proveedor'), ('commercial', 'Comercial'), ('lifecycle', 'Ciclo de vida')], default='', max_length=20)),
                ('variant_kind', models.CharField(blank=True, choices=[('position', 'Posición'), ('size', 'Medida'), ('kit', 'Kit'), ('material', 'Material'), ('spec', 'Especificación'), ('version', 'Versión'), ('color', 'Color'), ('package', 'Empaque'), ('descriptor', 'Descriptor'), ('market', 'Mercado'), ('alt_oem_tail', 'OEM alterno'), ('compound', 'Compuesto')], default='', max_length=20)),
                ('attribution', models.CharField(blank=True, default='', max_length=200)),
                ('creates_company_reference', models.BooleanField(default=False)),
                ('scope_overrides', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta')], default='low', max_length=6)),
                ('status', models.CharField(choices=[('seed_confirmed', 'Confirmado en la semilla'), ('needs_owner_confirmation', 'Por confirmar'), ('needs_owner_label', 'Por etiquetar'), ('owner_confirmed', 'Confirmado por el propietario')], default='needs_owner_label', max_length=30)),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('proposed_label', models.TextField(blank=True, default='')),
                ('legacy_company_registry', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(db_index=True, default=1)),
                ('alias_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='mall.catalogcodesuffix')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['token'],
            },
        ),
        migrations.CreateModel(
            name='CatalogCodeSuffixChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=60)),
                ('action', models.CharField(choices=[('seed_confirm', 'Confirmación del propietario en la semilla'), ('confirm_tag', 'Confirmar etiqueta'), ('set_variant', 'Marcar variante'), ('set_unknown', 'Marcar desconocido'), ('note', 'Notas'), ('add_alias', 'Agregar alias'), ('set_alias', 'Alias de otra etiqueta'), ('add_scope_override', 'Agregar alcance'), ('remove_scope_override', 'Quitar alcance')], max_length=30)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('suffix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='mall.catalogcodesuffix')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(('token', django.db.models.functions.text.Upper('token')), models.Q(('token', ''), _negated=True)), name='catalog_suffix_token_upper'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(('match__in', ['exact', 'shape'])), name='catalog_suffix_valid_match'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['seed_confirmed', 'needs_owner_confirmation', 'needs_owner_label', 'owner_confirmed'])), name='catalog_suffix_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__in', ['low', 'medium', 'high'])), name='catalog_suffix_valid_confidence'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cls', 'TAG'), ('tag_kind__in', ['company_code', 'brand', 'house_brand', 'origin', 'genuine', 'supplier_marker', 'commercial', 'lifecycle']), ('variant_kind', '')), models.Q(('cls', 'VARIANT'), ('tag_kind', ''), ('variant_kind__in', ['position', 'size', 'kit', 'material', 'spec', 'version', 'color', 'package', 'descriptor', 'market', 'alt_oem_tail', 'compound'])), models.Q(('cls', 'UNKNOWN'), ('tag_kind', ''), ('variant_kind', '')), _connector='OR'), name='catalog_suffix_class_kind'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffix',
            constraint=models.CheckConstraint(condition=models.Q(('alias_of', models.F('id')), _negated=True), name='catalog_suffix_not_own_alias'),
        ),
        migrations.AddIndex(
            model_name='catalogcodesuffixchange',
            index=models.Index(fields=['suffix', '-created_at'], name='catalog_suffix_change_idx'),
        ),
        migrations.AddConstraint(
            model_name='catalogcodesuffixchange',
            constraint=models.CheckConstraint(condition=models.Q(('action__in', ['seed_confirm', 'confirm_tag', 'set_variant', 'set_unknown', 'note', 'add_alias', 'set_alias', 'add_scope_override', 'remove_scope_override'])), name='catalog_suffix_change_valid_action'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
