# Generated by Django 5.2.17 on 2026-10-06 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0034_catalog_code_suffixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMFinderRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('dry_run', 'Simulación'), ('apply_auto', 'Aplicación automática'), ('ai', 'IA')], default='dry_run', max_length=12)),
                ('status', models.CharField(choices=[('running', 'En curso'), ('completed', 'Completada'), ('failed', 'Fallida')], default='running', max_length=10)),
                ('rules_version', models.CharField(max_length=40)),
                ('suffix_table_version', models.CharField(blank=True, default='', max_length=40)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('applied', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('timings', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OEMReviewCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('tier', models.CharField(db_index=True, max_length=30)),
                ('tier_rank', models.PositiveSmallIntegerField(default=0)),
                ('underlying_tier', models.CharField(blank=True, default='', max_length=30)),
                ('candidate', models.CharField(blank=True, default='', max_length=200)),
                ('written_form', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=40)),
                ('system', models.CharField(blank=True, default='', max_length=20)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('chain', models.CharField(blank=True, default='', max_length=300)),
                ('blockers', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('in_stock', models.BooleanField(default=False)),
                ('suffix_table_version', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('review', 'Por revisar'), ('applied', 'Aplicado'), ('dismissed', 'Descartado'), ('resolved', 'Resuelto')], db_index=True, default='review', max_length=10)),
                ('ai', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oem_review', to='mall.part')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='mall.oemfinderrun')),
            ],
            options={
                'ordering': ['-in_stock', 'tier_rank', 'id'],
                'indexes': [models.Index(fields=['status', 'tier_rank', '-in_stock'], name='oem_case_queue_idx'), models.Index(fields=['tier', 'brand', 'chain'], name='oem_case_batch_idx')],
            },
        ),
    ]
