# Generated by Django 5.2.17 on 2026-10-06 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0035_oem_finder'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMApplyHalt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('cleared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halts', to='mall.oemfinderrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OEMFinderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('AUTO_FLAG_CURRENT', 'El SKU ya es el OEM'), ('AUTO_RENAME_BASE', 'Renombrar a la base OEM'), ('STRONG_PENDING_OWNER_TAGS', 'Renombrar con etiquetas confirmadas por el propietario')], max_length=30)),
                ('method', models.CharField(choices=[('flag_current', 'Marcar el SKU actual como OEM'), ('rename_base', 'Renombrar a la base OEM'), ('rename_confirmed_tags', 'Renombrar a la base OEM (etiquetas confirmadas)')], max_length=24)),
                ('batch', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=120)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('undo', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('change', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='oem_finder', to='mall.catalogidentitychange')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oem_finder_changes', to='mall.part')),
                ('revert_change', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oem_finder_revert', to='mall.catalogidentitychange')),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='mall.oemfinderrun')),
            ],
            options={
                'ordering': ['run', 'batch', 'id'],
                'indexes': [models.Index(fields=['part', 'reverted_at'], name='oem_change_part_idx')],
            },
        ),
    ]
