# Generated by Django 5.2.17 on 2026-10-07 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0036_oem_finder_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Aprobar'), ('choose_oem', 'Elegir OEM'), ('send_to_merge', 'Enviar a Agrupar SKU'), ('dismiss', 'Descartar'), ('reopen', 'Reabrir'), ('reverted', 'Revertido'), ('apply_conflict', 'Rechazado al aplicar')], max_length=16)),
                ('tier', models.CharField(max_length=30)),
                ('fingerprint', models.CharField(max_length=64)),
                ('code', models.CharField(blank=True, default='', max_length=120)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='mall.oemreviewcase')),
                ('change', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to='mall.oemfinderchange')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mall.part')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_decisions', to='mall.oemfinderrun')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
