# Generated by Django 5.2.17 on 2026-10-07 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0037_oem_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMAutoCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(db_index=True, max_length=30)),
                ('apply_tier', models.CharField(choices=[('AUTO_FLAG_CURRENT', 'El SKU ya es el OEM'), ('AUTO_RENAME_BASE', 'Renombrar a la base OEM'), ('STRONG_PENDING_OWNER_TAGS', 'Renombrar con etiquetas confirmadas por el propietario')], max_length=30)),
                ('sku', models.CharField(max_length=200)),
                ('candidate', models.CharField(max_length=200)),
                ('written_form', models.CharField(blank=True, default='', max_length=200)),
                ('brand', models.CharField(blank=True, default='', max_length=40)),
                ('makes', models.JSONField(blank=True, default=list)),
                ('system', models.CharField(blank=True, default='', max_length=20)),
                ('grade', models.PositiveSmallIntegerField(default=0)),
                ('chain', models.CharField(blank=True, default='', max_length=300)),
                ('chain_tokens', models.JSONField(blank=True, default=list)),
                ('owner_tags', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('in_stock', models.BooleanField(default=False)),
                ('available_quantity', models.IntegerField(default=0)),
                ('fingerprint', models.CharField(max_length=64)),
                ('rules_version', models.CharField(max_length=40)),
                ('suffix_table_version', models.CharField(blank=True, default='', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('applied', 'Aplicado'), ('sent_to_review', 'Enviado a revisión'), ('excluded', 'Excluido hasta una decisión humana'), ('stale', 'Ya no es automático')], db_index=True, default='pending', max_length=16)),
                ('reason', models.CharField(blank=True, default='', max_length=40)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oem_auto', to='mall.part')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_candidates', to='mall.oemfinderrun')),
            ],
            options={
                'ordering': ['-in_stock', '-available_quantity', 'sku'],
                'indexes': [models.Index(fields=['status', 'tier', '-in_stock'], name='oem_auto_queue_idx'), models.Index(fields=['tier', 'brand', 'chain'], name='oem_auto_filter_idx')],
            },
        ),
    ]
