# Generated by Django 5.2.17 on 2026-10-07 06:08

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


def seed(apps, schema_editor):
    """Idempotent: one reference per (brand, compact code) of the OEM alternos already in the catalog, with the source each one's
    reference_source names (the 350 OEM finder rows of 2026-10-06 come in as inferred). Existing rows are merged, never duplicated."""
    from mall.catalog_suffixes import SuffixTable
    from mall.oem_reference import seed_from_partcodes
    seed_from_partcodes(apps.get_model('mall', 'OEMReference'), apps.get_model('mall', 'OEMReferenceSource'), apps.get_model('mall', 'PartCode'),
                        using=schema_editor.connection.alias, table=SuffixTable.from_fixture())


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0038_oem_auto_candidates'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=120, verbose_name='fabricante')),
                ('code', models.CharField(max_length=60, verbose_name='número OEM compacto')),
                ('printed_forms', models.JSONField(blank=True, default=list, verbose_name='formas impresas')),
                ('system', models.CharField(blank=True, default='', max_length=20, verbose_name='sistema de numeración')),
                ('family', models.CharField(blank=True, default='', max_length=20, verbose_name='familia')),
                ('part_type', models.CharField(blank=True, default='', max_length=60, verbose_name='tipo de pieza')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='descripción')),
                ('applications', models.TextField(blank=True, default='', verbose_name='aplicaciones')),
                ('status', models.CharField(choices=[('verified', 'Verificado'), ('declared', 'Declarado'), ('inferred', 'Inferido'), ('disputed', 'En disputa')], db_index=True, default='inferred', max_length=10, verbose_name='estado')),
                ('dispute_note', models.TextField(blank=True, default='', verbose_name='motivo de la disputa')),
                ('notes', models.TextField(blank=True, default='', verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='versión')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creada por')),
                ('superseded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='mall.oemreference', verbose_name='reemplazado por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizada por')),
            ],
            options={
                'verbose_name': 'referencia OEM',
                'verbose_name_plural': 'referencias OEM',
                'ordering': ['manufacturer', 'code'],
            },
        ),
        migrations.CreateModel(
            name='OEMReferenceSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('price_list', 'Lista de precios de distribuidor'), ('manufacturer_catalog', 'Catálogo del fabricante'), ('aftermarket_catalog', 'Catálogo de marca de repuesto'), ('ai_lookup', 'Búsqueda OEM con IA'), ('supplier_declaration', 'Declaración de proveedor'), ('catalog_approval', 'Aprobación en el catálogo'), ('oem_finder', 'Buscador OEM'), ('manual', 'Registro manual')], max_length=24, verbose_name='tipo de fuente')),
                ('citation', models.CharField(blank=True, default='', max_length=500, verbose_name='cita')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='mall.oemreference', verbose_name='referencia')),
            ],
            options={
                'verbose_name': 'fuente de referencia OEM',
                'verbose_name_plural': 'fuentes de referencias OEM',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='oemreference',
            index=models.Index(fields=['code'], name='oem_reference_code_idx'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'code'), name='oem_reference_unique_number'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.CheckConstraint(condition=models.Q(('code__regex', '^[0-9A-Z]+$')), name='oem_reference_code_compact'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.CheckConstraint(condition=models.Q(('manufacturer', django.db.models.functions.text.Upper('manufacturer')), models.Q(('manufacturer', ''), _negated=True)), name='oem_reference_manufacturer_upper'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['verified', 'declared', 'inferred', 'disputed'])), name='oem_reference_valid_status'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'disputed'), _negated=True), models.Q(('dispute_note', ''), _negated=True), _connector='OR'), name='oem_reference_dispute_note'),
        ),
        migrations.AddConstraint(
            model_name='oemreference',
            constraint=models.CheckConstraint(condition=models.Q(('superseded_by', models.F('id')), _negated=True), name='oem_reference_not_own_superseder'),
        ),
        migrations.AddConstraint(
            model_name='oemreferencesource',
            constraint=models.UniqueConstraint(fields=('reference', 'kind', 'citation'), name='oem_reference_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='oemreferencesource',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['price_list', 'manufacturer_catalog', 'aftermarket_catalog', 'ai_lookup', 'supplier_declaration', 'catalog_approval', 'oem_finder', 'manual'])), name='oem_reference_source_valid_kind'),
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
