# Generated by Django 5.2.17 on 2026-10-07 17:34

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    from mall.oem_reference import link_partcodes
    link_partcodes(apps.get_model('mall', 'OEMReference'), apps.get_model('mall', 'PartCode'), using=schema_editor.connection.alias)


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0039_oem_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='partcode',
            name='oem_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternos', to='mall.oemreference', verbose_name='referencia OEM'),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
