# Generated by Django 5.2.17 on 2026-10-08 06:09

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0040_partcode_oem_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OEMCrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=120, verbose_name='marca')),
                ('code', models.CharField(max_length=120, verbose_name='código')),
                ('number', models.CharField(max_length=120, verbose_name='código compacto')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='citas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_references', to='mall.oemreference', verbose_name='referencia OEM')),
            ],
            options={
                'verbose_name': 'equivalencia de posventa',
                'verbose_name_plural': 'equivalencias de posventa',
                'ordering': ['brand', 'number', 'id'],
                'indexes': [models.Index(fields=['number'], name='oem_cross_reference_number_idx')],
                'constraints': [models.UniqueConstraint(fields=('reference', 'brand', 'number'), name='oem_cross_reference_unique'), models.CheckConstraint(condition=models.Q(('number__regex', '^[0-9A-Z]+$')), name='oem_cross_reference_number_compact'), models.CheckConstraint(condition=models.Q(('brand', django.db.models.functions.text.Upper('brand')), models.Q(('brand', ''), _negated=True)), name='oem_cross_reference_brand_upper')],
            },
        ),
        migrations.CreateModel(
            name='PartOEMLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sku_name', 'Nombre del SKU'), ('catalog', 'Catálogo de marca de repuesto')], max_length=12, verbose_name='origen')),
                ('citations', models.JSONField(blank=True, default=list, verbose_name='citas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de registro')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oem_links', to='mall.part', verbose_name='repuesto del catálogo')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_links', to='mall.oemreference', verbose_name='referencia OEM')),
            ],
            options={
                'verbose_name': 'vínculo de SKU con número OEM',
                'verbose_name_plural': 'vínculos de SKU con números OEM',
                'ordering': ['part', 'reference', 'source'],
                'constraints': [models.UniqueConstraint(fields=('part', 'reference', 'source'), name='part_oem_link_unique'), models.CheckConstraint(condition=models.Q(('source__in', ['sku_name', 'catalog'])), name='part_oem_link_valid_source')],
            },
        ),
    ]
