'use client';

import { useId, useRef } from 'react';
import { ArrowDownLeft, ArrowUpRight, CheckCircle2, Download, FileSpreadsheet, LoaderCircle, Pause, Play } from 'lucide-react';
import Modal from './modal';
import { useResumableImport } from './use-resumable-import';
import { Account, SupplierInventoryImportResult } from '@/lib/types';

export default function SupplierInventoryImport({ account, onClose, onSaved }: { account: Account; onClose: () => void; onSaved: (result: SupplierInventoryImportResult) => void }) {
  const fileInput = useRef<HTMLInputElement>(null);
  const fileId = useId();
  const base = `/api/market/accounts/${account.id}/inventory/import`;
  const { file, result, pendingJob, busy, error, needsReview, pausing, interrupted, completed, expired, jobUrl, isOperating, review, recover, importBatches, selectFile, requestPause } =
    useResumableImport<SupplierInventoryImportResult>({ base, storageKey: `motionpartes.supplier-import-job:${account.id}`, onCompleted: onSaved,
      emptyMessage: 'No hay filas válidas para importar. Descarga y corrige las filas con errores.' });

  const progress = result?.progress;
  const canImport = !!result?.valid && !!pendingJob && !!progress?.total_batches && !completed && !needsReview && !expired;
  const close = () => { if (!isOperating()) onClose(); };
  const units = (value: number) => value.toLocaleString('es-PA');
  return <Modal title="Importar existencias desde Excel" wide onClose={close}><div className="supplier-import">
    <p className="modal-description">Carga los saldos totales de {account.name}. La revisión no modifica existencias; verás cada crédito o débito antes de confirmar. Al terminar la carga, los códigos se agrupan automáticamente con el catálogo; las coincidencias dudosas quedan para revisión.</p>
    <div className="supplier-import-template"><a className="button soft small" href={`${base}/template`} download><Download size={16}/>Descargar plantilla</a><p>Columnas obligatorias: <strong>ID_INVENTARIO_PROVEEDOR, CODIGO y EXISTENCIAS</strong>. MARCA, DESCRIPCION y REFERENCIAS son opcionales. En REFERENCIAS separa los alternos con punto y coma: HYUNDAI:51712-1R000; KIA:51712-0U000. El fabricante es opcional. Estas referencias ayudan a encontrar el SKU maestro y no crean artículos adicionales. Sustituye la fila de ejemplo.</p></div>
    <form onSubmit={review} autoComplete="off" className="supplier-import-form">
      <label htmlFor={fileId}>Archivo Excel de existencias</label>
      <div className="supplier-import-picker"><input ref={fileInput} id={fileId} type="file" accept=".xlsx" className="sr-only" disabled={!!busy} onChange={event => selectFile(event.target.files?.[0] || null)}/><button className="button soft small" type="button" disabled={!!busy} onClick={() => fileInput.current?.click()}><FileSpreadsheet size={16}/>{result || pendingJob ? 'Elegir otro archivo' : 'Seleccionar archivo'}</button><span>{file?.name || result?.filename || 'Ningún archivo seleccionado'}</span></div>
      <p className="form-footnote">Formato .xlsx, hasta 5 MB, sin límite de filas. Conserva los ID y códigos como texto. EXISTENCIAS es el saldo total: cero vacía ese artículo; los artículos omitidos conservan su saldo. Los registros de apiag-cloud se actualizan por su integración.</p>
      <button className="button soft full" disabled={!file || !!busy}>{busy === 'review' ? <LoaderCircle className="spin" size={17}/> : <FileSpreadsheet size={17}/>}Revisar archivo</button>
    </form>
    {busy === 'recover' && <div className="loading" role="status"><LoaderCircle className="spin"/>Recuperando tu importación…</div>}
    {error && <div className="notice error" role="alert">{error}{needsReview && <p>Selecciona el archivo y revísalo de nuevo. Los lotes ya guardados se conservarán.</p>}</div>}
    {pendingJob && !result && !busy && <button className="button soft" onClick={() => recover(pendingJob)}>Recuperar progreso</button>}
    {result && <div className="supplier-import-preview">
      <div className="supplier-import-preview-heading"><h3>{completed ? 'Importación completada' : 'Vista previa'}</h3><span>{result.filename}</span></div>
      {completed && <div className="notice success" role="status"><CheckCircle2 size={18}/><span>Se procesaron {units(result.applied_summary.valid_rows)} filas válidas: {units(result.applied_summary.created_items)} artículos nuevos, {units(result.applied_summary.updated_items)} actualizados y {units(result.applied_summary.unchanged_items)} sin cambios.{result.summary.rejected_rows > 0 && ` ${units(result.summary.rejected_rows)} filas siguen pendientes; puedes descargar sus errores y cargar el archivo corregido.`}</span></div>}
      <div className="supplier-import-summary"><span><strong>{units(result.summary.valid_rows)}</strong>Filas válidas</span><span><strong>{units(result.summary.rejected_rows)}</strong>Filas pendientes</span><span><strong>{units(result.summary.created_items)}</strong>Artículos nuevos</span><span><strong>{units(result.summary.updated_items)}</strong>{completed ? 'Artículos actualizados' : 'Artículos por actualizar'}</span><span className="credit"><strong>{units(result.summary.credit_units)}</strong>Unidades de crédito</span><span className="debit"><strong>{units(result.summary.debit_units)}</strong>Unidades de débito</span></div>
      {result.summary.rejected_rows > 0 && <div className="supplier-import-errors"><div className="notice error">{units(result.summary.rejected_rows)} {result.summary.rejected_rows === 1 ? 'fila con errores queda' : 'filas con errores quedan'} fuera de esta importación. Puedes importar las válidas y corregir las demás después.</div><a className="button soft small" href={`${jobUrl(result.job_id)}/errors`} download><Download size={16}/>Descargar filas con errores</a><p className="form-footnote">El archivo contiene todas las filas pendientes y sus errores. Corrígelo y cárgalo aquí de nuevo; no necesitas volver a cargar las filas importadas.</p><details><summary>Ver errores{result.error_count > result.errors.length ? ` · primeros ${result.errors.length} de ${units(result.error_count)}` : ''}</summary><div className="table-scroll"><table><thead><tr><th>Fila</th><th>Columna</th><th>Error</th></tr></thead><tbody>{result.errors.map((item, index) => <tr key={`${item.row}-${item.column}-${index}`}><td>{item.row}</td><td>{item.column}</td><td>{item.message}</td></tr>)}</tbody></table></div></details></div>}
      {result.warning_count > 0 && <details className="supplier-import-warnings"><summary>{units(result.warning_count)} advertencias de lectura</summary><ul>{result.warnings.map((item, index) => <li key={`${item.row}-${index}`}>Fila {item.row} · {item.column}: {item.message}</li>)}</ul>{result.warning_count > result.warnings.length && <p>Se muestran las primeras {result.warnings.length} advertencias.</p>}</details>}
      {!!progress?.total_batches && <div className="supplier-import-progress" aria-live="polite"><div><strong>{busy === 'import' ? pausing ? 'Pausando después de este lote…' : 'Importando existencias…' : completed ? 'Todos los lotes guardados' : progress.completed_batches ? 'Importación en pausa' : 'Lista para importar'}</strong><span>{units(progress.processed_rows)} de {units(progress.total_rows)} filas · {progress.completed_batches} de {progress.total_batches} lotes</span></div><progress aria-label="Progreso de importación de existencias" value={progress.completed_batches} max={progress.total_batches}/>{busy === 'import' && <button type="button" className="button soft small" disabled={pausing} onClick={requestPause}><Pause size={15}/>Pausar después del lote</button>}</div>}
      {expired && !completed && <p className="notice error">Esta revisión ha caducado. Selecciona el archivo y revísalo de nuevo para importar; los lotes ya guardados se conservan.</p>}
      {result.preview.length > 0 && <><p className="supplier-import-preview-caption">{result.preview_count > result.preview.length ? `Se muestran las primeras ${result.preview.length} de ${units(result.preview_count)} filas válidas.` : `${units(result.preview_count)} filas válidas en la vista previa.`} Cada movimiento usa una cantidad positiva; su dirección indica si aumenta o reduce las existencias.</p><div className="table-scroll supplier-import-table"><table><thead><tr><th>Fila / ID del proveedor</th><th>Código / repuesto</th><th>Saldo actual</th><th>Saldo en Excel</th><th>Movimiento</th><th>Cantidad</th><th>Nuevo saldo</th><th>Acción</th></tr></thead><tbody>{result.preview.map(item => <tr key={item.row}><td><span>Fila {item.row}</span><strong>{item.supplier_invent_id}</strong></td><td><strong>{item.codigo}</strong><span>{item.brand || 'SIN MARCA'}{item.description ? ` · ${item.description}` : ''}</span><small>{item.references?.length ? `REFERENCIAS: ${item.references.map(ref => [ref.brand, ref.code].filter(Boolean).join(': ')).join('; ')}` : ''}</small><small>{item.part_sku ? `SKU: ${item.part_sku}` : item.matching_status === 'review' ? 'Coincidencia por revisar' : 'Coincidencia pendiente'}</small></td><td className="number-cell">{units(item.current_quantity)}</td><td className="number-cell">{units(item.uploaded_quantity)}</td><td><span className={`supplier-movement ${item.direction}`}>{item.direction === 'credit' ? <><ArrowDownLeft size={14}/>Crédito</> : item.direction === 'debit' ? <><ArrowUpRight size={14}/>Débito</> : 'Sin cambio'}</span></td><td className="number-cell">{units(item.movement_quantity)}</td><td className="number-cell"><strong>{units(item.new_quantity)}</strong></td><td>{item.action === 'create' ? 'Crear' : item.action === 'update' ? 'Actualizar' : 'Sin cambios'}</td></tr>)}</tbody></table></div></>}
      {completed ? <button type="button" className="button primary full" onClick={close}>Cerrar</button> : <button type="button" className="button primary full" disabled={!canImport || !!busy} onClick={importBatches}>{busy === 'import' ? <LoaderCircle className="spin" size={17}/> : interrupted || progress?.completed_batches ? <Play size={17}/> : <CheckCircle2 size={17}/>} {interrupted || progress?.completed_batches ? 'Reanudar importación' : result.summary.rejected_rows ? 'Importar filas válidas' : 'Confirmar importación'}</button>}
      {busy === 'import' && <p className="form-footnote">Espera a que termine o pausa después del lote antes de cerrar. Puedes reanudar el progreso guardado al volver a abrir este panel.</p>}
    </div>}
  </div></Modal>;
}
