import { expect, test } from '@playwright/test';

test.use({ actionTimeout: 10000 });
const origin = process.env.E2E_BASE_URL || 'http://localhost:8080';
for (const size of [{ name: 'desktop', width: 1440, height: 1000 }, { name: 'mobile', width: 390, height: 844 }]) {
  test(`${size.name}: configure a subgroup template and save specifications with vehicle applications`, async ({ page }) => {
    test.skip(!process.env.E2E_TECHNICAL_TOKEN, 'Requires a disposable superuser fixture.');
    test.setTimeout(90000);
    await page.context().addCookies([{ name: 'partsmall_session', value: process.env.E2E_TECHNICAL_TOKEN!, url: origin, httpOnly: true, sameSite: 'Strict' }]);
    await page.setViewportSize(size);
    const suffix = `TECH-E2E-${process.env.E2E_TECHNICAL_RUN}-${size.name}`.toUpperCase();
    await page.goto('/administracion?seccion=plantillas');
    await page.getByRole('button', { name: 'Crear subgrupo', exact: true }).click();
    let dialog = page.getByRole('dialog');
    await dialog.getByLabel('Grupo', { exact: true }).fill('FRENOS E2E');
    await dialog.getByLabel('Subgrupo / tipo de repuesto').fill(suffix);
    await dialog.getByRole('button', { name: 'Guardar subgrupo' }).click();
    await expect(dialog).not.toBeVisible();
    await page.getByLabel('Buscar grupo o subgrupo').fill(suffix);
    await page.getByRole('button', { name: 'Configurar plantilla' }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByRole('button', { name: 'Agregar campo' }).click();
    await dialog.getByLabel('Nombre del campo', { exact: true }).fill('DIÁMETRO EXTERIOR');
    await dialog.getByLabel('Identificador estable').fill('diameter');
    await dialog.getByRole('combobox', { name: 'Unidad', exact: true }).selectOption('mm');
    await dialog.getByLabel('Necesario para completar la ficha').check();
    await dialog.getByRole('button', { name: 'Agregar campo' }).click();
    const cards = dialog.locator('.technical-field-card');
    await cards.nth(1).getByLabel('Nombre del campo', { exact: true }).fill('ENCODER ABS');
    await cards.nth(1).getByLabel('Identificador estable').fill('abs');
    await cards.nth(1).getByLabel('Tipo de dato').selectOption('boolean');
    await dialog.getByRole('button', { name: 'Guardar plantilla' }).click();
    await expect(dialog.getByRole('status')).toHaveText('Plantilla guardada.');
    await dialog.screenshot({ path: `/tmp/motionpartes-template-${size.name}.png` });
    await dialog.getByRole('button', { name: 'Cerrar ventana', exact: true }).click();
    const types = await (await page.request.get(`/api/management/part-types?search=${suffix}`)).json();
    const type = types.results[0];
    await page.goto('/administracion?seccion=aplicaciones');
    await page.getByRole('button', { name: 'Crear aplicación', exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('Marca del vehículo').fill('HYUNDAI');
    await dialog.getByLabel('Modelo', { exact: true }).fill(suffix);
    await dialog.getByLabel('Año desde').fill('2011');
    await dialog.getByLabel('Año hasta').fill('2016');
    await dialog.getByRole('button', { name: 'Guardar aplicación' }).click();
    await expect(dialog).not.toBeVisible();
    const created = await page.request.post('/api/management/catalog', { headers: { Origin: origin }, data: { sku: suffix, part_type: type.id, active: true } });
    expect(created.status()).toBe(201);
    const part = await created.json();
    await page.goto('/administracion?seccion=inventario');
    await page.getByLabel('Buscar repuestos', { exact: true }).fill(suffix);
    await page.getByRole('button', { name: `Ficha técnica de ${suffix}`, exact: true }).click();
    dialog = page.getByRole('dialog');
    await dialog.getByLabel('DIÁMETRO EXTERIOR (mm) · NECESARIO', { exact: true }).fill('256');
    await dialog.getByRole('combobox', { name: 'ENCODER ABS', exact: true }).selectOption('false');
    await dialog.getByLabel('Buscar aplicación para vincular').fill(suffix);
    await dialog.getByRole('button', { name: 'Vincular', exact: true }).click();
    await dialog.getByLabel('Posición', { exact: true }).fill('DELANTERO');
    await dialog.getByLabel('Condiciones de aplicación').fill('SOLO CON ABS');
    await dialog.getByLabel('Compatibilidad verificada').check();
    await dialog.getByRole('button', { name: 'Guardar ficha técnica' }).click();
    await expect(dialog).not.toBeVisible();
    await page.reload();
    await page.getByLabel('Buscar repuestos', { exact: true }).fill(suffix);
    await page.getByRole('button', { name: `Ficha técnica de ${suffix}`, exact: true }).click();
    dialog = page.getByRole('dialog');
    await expect(dialog.getByLabel('DIÁMETRO EXTERIOR (mm) · NECESARIO', { exact: true })).toHaveValue('256');
    await expect(dialog.getByRole('combobox', { name: 'ENCODER ABS', exact: true })).toHaveValue('false');
    await expect(dialog.getByLabel('Compatibilidad verificada')).toBeChecked();
    await dialog.screenshot({ path: `/tmp/motionpartes-sheet-${size.name}.png` });
    const overflow = await dialog.evaluate(el => el.scrollWidth > el.clientWidth + 1);
    expect(overflow).toBe(false);
    const publicSheet = await page.request.get(`/api/market/catalog/${part.id}/technical`);
    expect(publicSheet.status()).toBe(200);
    const result = await publicSheet.json();
    expect(result.values.abs.value).toBe(false);
    expect(result.values.diameter.value).toBe('256');
    expect(result.applications).toHaveLength(1);
  });
}
